# DPGF Resume CCTP - HTTP vhost used before and after certificate issuance.
<VirtualHost *:80>
    ServerName dpgf.moduo.fr

    ErrorLog ${APACHE_LOG_DIR}/dpgf-error.log
    CustomLog ${APACHE_LOG_DIR}/dpgf-access.log combined

    RewriteEngine On
    RewriteCond %{SERVER_NAME} =dpgf.moduo.fr
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
